name: Fetch Data

on:
  push:
    branches:
      - master  # Modifiez ici la branche de déclenchement

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      env:
        API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: python scripts/fetch_weather.py
